#!/bin/bash

export TMPNAME=nmon_dir.$$
export NMON_TMPDIR=~/$TMPNAME

mkdir -p $NMON_TMPDIR
currpwd=`pwd`

echo "sparksbw1 output"
srcfile=`~/scripts/get_nmon.sh`
cp $srcfile $NMON_TMPDIR/
echo "==========================================================="
echo "sparksbw2 output"
srcfile=`ssh baidu@sparksbw2 ~/scripts/get_nmon.sh`
scp baidu@sparksbw2:$srcfile $NMON_TMPDIR/
echo "==========================================================="
echo "sparksbw3 output"
srcfile=`ssh baidu@sparksbw3 ~/scripts/get_nmon.sh`
scp baidu@sparksbw3:$srcfile $NMON_TMPDIR/
echo "==========================================================="
echo "sparksbw4 output"
srcfile=`ssh baidu@sparksbw4 ~/scripts/get_nmon.sh`
scp baidu@sparksbw4:$srcfile $NMON_TMPDIR/
echo "==========================================================="

cd ~

tar zcf $currpwd/$TMPNAME.tar.gz ./$TMPNAME

cd $currpwd

rm -rf $NMON_TMPDIR

echo "Tar file found under : $TMPNAME.tar.gz "


